// Package controllers provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package controllers

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// GeneratedResponse defines model for GeneratedResponse.
type GeneratedResponse []Response

// Response defines model for Response.
type Response struct {
	Data   *[]int   `json:"data,omitempty"`
	Stddev *float32 `json:"stddev,omitempty"`
}

// GetRandomMeanParams defines parameters for GetRandomMean.
type GetRandomMeanParams struct {
	Requests int `json:"requests"`
	Length   int `json:"length"`
}
