name: Tests
on:
  push:
    branches:
      - '*'
jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make unit_test
  end2end-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start